# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-21 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '\u5546\u54c1\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=32, verbose_name='\u6536\u8d27\u7535\u8bdd')),
                ('name', models.CharField(max_length=16, verbose_name='\u6536\u8d27\u4eba\u59d3\u540d')),
                ('is_default', models.BooleanField(default=False, verbose_name='\u9ed8\u8ba4\u6536\u8d27\u5730\u5740')),
                ('detail_address', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='\u8be6\u7ec6\u5730\u5740')),
                ('area_address', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='\u533a\u57df\u5730\u5740')),
                ('area_code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='\u533a\u57df\u7f16\u53f7')),
                ('postalcode', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='\u90ae\u653f\u7f16\u7801')),
            ],
            options={
                'verbose_name_plural': '\u6536\u8d27\u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, verbose_name='\u5546\u54c1\u540d\u5b57')),
                ('picture', models.CharField(blank=True, default='http://static.fibar.cn/baoshihua.png', max_length=128, null=True, verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('current_nums', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u5e93\u5b58')),
                ('unit', models.CharField(max_length=32, verbose_name='\u5546\u54c1\u5355\u4f4d')),
                ('price', models.FloatField(default=0.0, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('priority', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u6743\u91cd\uff0c\u8d8a\u5927\u8d8a\u4f18\u5148\u5c55\u793a')),
                ('picture_url', models.ImageField(blank=True, default='', null=True, upload_to='photo')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_good', to='xjmallapp.Classification', verbose_name='\u5546\u54c1\u7c7b\u522b')),
            ],
            options={
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('order_num', models.CharField(max_length=64, unique=True, verbose_name='\u8ba2\u5355\u53f7')),
                ('is_check', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5ba1\u6838')),
                ('express_num', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5feb\u9012\u53f7')),
                ('express_cost', models.FloatField(default=0.0, verbose_name='\u8fd0\u8d39')),
                ('total_price', models.FloatField(default=0.0, verbose_name='\u8ba2\u5355\u603b\u4ef7')),
                ('is_delivery', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6536\u8d27\uff0c\u9ed8\u8ba4\u8d85\u8fc7\u4e03\u5929\u81ea\u52a8\u6536\u8d27')),
                ('address', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='\u6536\u8d27\u4fe1\u606f')),
                ('is_revoke', models.BooleanField(default=False, verbose_name='\u662f\u5426\u88ab\u9a73\u56de')),
            ],
            options={
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('numbers', models.IntegerField(default=0, verbose_name='\u8ba2\u5355\u5355\u4e2a\u5546\u54c1\u6570\u91cf')),
                ('total_price', models.FloatField(default=0.0)),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_orderitem', to='xjmallapp.Order', verbose_name='\u6240\u5c5e\u8ba2\u5355')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_orderitem', to='xjmallapp.Good', verbose_name='\u8ba2\u5355\u5355\u4e2a\u5546\u54c1')),
            ],
            options={
                'verbose_name_plural': '\u8ba2\u5355\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='SellerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, verbose_name='\u9500\u552e\u4ee3\u8868\u7684\u540d\u5b57')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u9500\u552e\u4ee3\u8868\u7684\u7535\u8bdd')),
                ('account', models.CharField(max_length=64, unique=True, verbose_name='\u9500\u552e\u4ee3\u8868\u7684\u8d26\u53f7,6-20\u4f4d')),
                ('password', models.CharField(max_length=128, verbose_name='\u9500\u552e\u4ee3\u8868\u7684\u5bc6\u7801,6-20\u4f4d')),
                ('area', models.CharField(max_length=64, verbose_name='\u5730\u533a')),
                ('user_type', models.IntegerField(choices=[(0, '\u9500\u552e\u4ee3\u8868'), (1, '\u7ba1\u7406\u5458')], default=0, verbose_name='\u7528\u6237\u7c7b\u578b')),
                ('icon_phone', models.CharField(default='http://static.fibar.cn/icon_phone1.png', max_length=128, verbose_name='\u7535\u8bdd\u5c0f\u56fe\u6807')),
            ],
            options={
                'verbose_name_plural': '\u9500\u552e\u4ee3\u8868',
            },
        ),
        migrations.CreateModel(
            name='SellerUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=128)),
                ('selleruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selleruser_token', to='xjmallapp.SellerUser', verbose_name='\u9500\u552e\u4eba\u5458token')),
            ],
            options={
                'verbose_name_plural': 'token\u9500\u552e\u4ee3\u8868',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('numbers', models.IntegerField(default=0, verbose_name='\u8d2d\u7269\u8f66\u5355\u4e2a\u5546\u54c1\u6570\u91cf')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_shoppingcard', to='xjmallapp.Good', verbose_name='\u8d2d\u7269\u8f66\u5546\u54c1')),
            ],
            options={
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(max_length=64, verbose_name='\u9500\u552e\u4ee3\u8868\u7684\u8d26\u53f7,6-20\u4f4d')),
                ('password', models.CharField(max_length=128, verbose_name='\u9500\u552e\u4ee3\u8868\u7684\u5bc6\u7801,6-20\u4f4d')),
                ('name', models.CharField(max_length=128, verbose_name='\u6ce8\u518c\u4eba\u540d\u5b57')),
                ('store_name', models.CharField(max_length=128, unique=True, verbose_name='\u7ec8\u7aef\u5e97\u540d\u5b57')),
                ('virtual_coin_limit', models.IntegerField(blank=True, choices=[(0, 5000.0), (1, 50000.0)], null=True, verbose_name='\u989d\u5ea6')),
                ('virtual_coin_canuse', models.FloatField(default=0.0, verbose_name='\u53ef\u4f7f\u7528\u7684\u989d\u5ea6')),
                ('is_check', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5ba1\u6838\u4e86')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7ec8\u7aef\u5e97\u5730\u5740')),
                ('selleruser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selleruser_store', to='xjmallapp.SellerUser', verbose_name='\u6240\u5c5e\u9500\u552e\u4ee3\u8868')),
            ],
            options={
                'verbose_name_plural': '\u7ec8\u7aef\u5e97',
            },
        ),
        migrations.CreateModel(
            name='StoreToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=128)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_token', to='xjmallapp.Store', verbose_name='\u7ec8\u7aef\u5e97\u4eba\u5458token')),
            ],
            options={
                'verbose_name_plural': 'token\u7ec8\u7aef\u5e97',
            },
        ),
        migrations.AddField(
            model_name='shoppingcard',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_shoppingcard', to='xjmallapp.Store', verbose_name='\u6240\u5c5e\u7ec8\u7aef\u5e97'),
        ),
        migrations.AddField(
            model_name='order',
            name='check_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkuser_order', to='xjmallapp.SellerUser', verbose_name='\u5ba1\u6838\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storebelong_order', to='xjmallapp.Store', verbose_name='\u8ba2\u5355\u6240\u5c5e\u95e8\u5e97'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_deliveryaddress', to='xjmallapp.Store', verbose_name='\u6240\u5c5e\u5e97\u94fa'),
        ),
    ]
