# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-28 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xjmallapp', '0002_auto_20190222_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xjmallapp.Good')),
            ],
            options={
                'verbose_name_plural': '\u5546\u54c1\u7f16\u7801',
            },
        ),
    ]
