# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-28 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xjmallapp', '0003_goodcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('good', models.ManyToManyField(to='xjmallapp.Good')),
            ],
            options={
                'verbose_name_plural': '\u591a\u5bf9\u591a\u5546\u54c1\u79cd\u7c7b',
            },
        ),
    ]
